// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDe3O083srcvBFMf4f0VMoVo0ddwpEBoM',
    appId: '1:785136091962:web:0350426aa42085a68c8603',
    messagingSenderId: '785136091962',
    projectId: 'shoqandaaa',
    authDomain: 'shoqandaaa.firebaseapp.com',
    storageBucket: 'shoqandaaa.firebasestorage.app',
    measurementId: 'G-Z52TCGVXGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC068IgxGzvXh9uAt-U-Tz_viHGa69kiGE',
    appId: '1:785136091962:android:0acb92f8aa40e8778c8603',
    messagingSenderId: '785136091962',
    projectId: 'shoqandaaa',
    storageBucket: 'shoqandaaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD61scO5JJelg2cYVXHGxxv8L4AvAjzF4o',
    appId: '1:785136091962:ios:0308da9ae7885c7a8c8603',
    messagingSenderId: '785136091962',
    projectId: 'shoqandaaa',
    storageBucket: 'shoqandaaa.firebasestorage.app',
    iosBundleId: 'com.example.shoqandafinview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD61scO5JJelg2cYVXHGxxv8L4AvAjzF4o',
    appId: '1:785136091962:ios:0308da9ae7885c7a8c8603',
    messagingSenderId: '785136091962',
    projectId: 'shoqandaaa',
    storageBucket: 'shoqandaaa.firebasestorage.app',
    iosBundleId: 'com.example.shoqandafinview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDe3O083srcvBFMf4f0VMoVo0ddwpEBoM',
    appId: '1:785136091962:web:afcf83fd8d721b428c8603',
    messagingSenderId: '785136091962',
    projectId: 'shoqandaaa',
    authDomain: 'shoqandaaa.firebaseapp.com',
    storageBucket: 'shoqandaaa.firebasestorage.app',
    measurementId: 'G-MTXTP0SW8V',
  );

}